#######################################################################################
#                                                                                     #
#                                Data Pipeline Settings                               #
#                                                                                     #
#######################################################################################


# Specify data to extract and load
extract:
    - filepath: "input/demand"
      test_size:
      data:
          - "final_households.csv"
          - "final_persons.csv"
          - "final_trips.csv"
    - filepath: "input/supply"
      test_size:
      data:
          - "dist.omx"

# Specify transformation steps
transform:
    processor: "config/processor.csv"
    summarizer: "config/expressions.csv"
    steps:
        #Preprocess
        - name: step_0
          process: True

        - name: step_1
          merge:
              - table_name: hhper
                include:
                    - final_households
                    - final_persons
                merge_cols:
                    - household_id
                    - household_id
                merge_type: left

        #Summarize
        - name: step_2
          summarize: True

        #Postprocess
        - name: step_3
          process: True

load:
    outdir: "output/"
    empty_fill: 0