#######################################################################################
#                                                                                     #
#                                Data Pipeline Settings                               #
#                                                                                     #
#######################################################################################


# Specify data to extract and load
extract:
    - filepath: "D:/Models/RSM/visualizer/SimWrapper/data/external"
      test_size: 
      data:
          - "persons.csv"
          - "households.csv"
          - "individualTrips.csv"
          - "jointTrips.csv"
          - "transit_onoff.csv"

# Specify transformation steps
transform:
    processor: "config/processor.csv"
    summarizer: "config/expressions.csv"
    steps:
        - name: step_1
          concat:
              - table_name: trips
                include:
                    - individualTrips
                    - jointTrips
          process: True
          
        - name: step_2
          summarize: True
          process: True

load:
    outdir: "D:/Models/RSM/visualizer/SimWrapper/data/processed/"
    empty_fill: 0